# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000

        Fsb\Media\FilesIndexBundle\Entity\User:
            algorithm:            pbkdf2
            hash_algorithm:       sha512
            encode_as_base64:     true
            iterations:           1000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: V7TnTp9d0ORN7prayMwjP+Nygj7A6mOWtYw7NrkDD0fye9e7Un44OA==
                        roles: [ 'ROLE_ADMIN' ]

        fsb_media_files_index_users:
            entity:
                class: Fsb\Media\FilesIndexBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        fsb_media_files_index_admin_login:
            pattern:  ^/admin/login$
            security: false

        fsb_media_files_index_admin:
            pattern:  ^/admin
            provider: in_memory
            form_login:
                check_path: fsb_media_files_index_admin_security_check
                login_path: fsb_media_files_index_admin_login
            logout:
                path:   fsb_media_files_index_admin_logout
                target: fsb_media_files_index_admin_homepage

        fsb_media_files_index_login:
            pattern:  ^/login$
            security: false

        fsb_media_files_index:
            pattern:  ^/
            provider: fsb_media_files_index_users
            anonymous: ~
            form_login:
                check_path: fsb_media_files_index_security_check
                login_path: fsb_media_files_index_login
            logout:
                path:   fsb_media_files_index_logout
                target: fsb_media_files_index_homepage

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }